# The version text sensor platform exposes the ESPHome version the firmware was compiled against as a text sensor.
# https://esphome.io/components/text_sensor/version.html
platform  : version
name      : "${devicelocation} Version"
